security:
    # comment est encrypté le mot de passe pour User :
    encoders:
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        db:
            # les utilisateurs viennent de l'entité User
            # et l'identifiant est l'email
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy

            # provider défini au-dessus dans le bloc providers
            provider: db

            # sur tout le site
            pattern: ^/

            # route du formulaire
            form_login:
                login_path: app_user_login
                check_path: app_user_login
                default_target_path: index2

            # route de la page de deconnexion
            logout:
                path: app_user_logout



            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
#         - { path: ^/profile, roles: ROLE_USER }
